[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_RAWG_API_KEY = "a52f7654d212491c82e635495ba2129a"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 